server:
  port: 8084

spring:
  datasource:
    druid:
      username: root
      password: 1234
      #url中database为对应的数据库名称
      url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bijian.bookmanage.domain
  configuration:
    map-underscore-to-camel-case: true

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

#showSql
logging:
  level:
    com.example.demo.mapper: debug

# swagger
swagger:
  base-package: com.bijian.bookmanage.controller
  base-path: /**
  title: 图书管理系统

oss:
  accessKeyId: LTAI4GKmuHYLdKoYfrCWwAbQ
  accessKeySecret: 1lgBaDmX7vO9GuNgM7DQr9v3VklQc7
  bucketName: bookmanage